//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17626
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50522.1
// 
namespace ViewTvProgram.iEPGService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvProgram", Namespace="http://schemas.datacontract.org/2004/07/iEPG.Entity")]
    public partial class TvProgram : ViewTvProgram.iEPGService.TvProgramBase {
        
        private byte ReserveStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ReserveStatus {
            get {
                return this.ReserveStatusField;
            }
            set {
                if ((this.ReserveStatusField.Equals(value) != true)) {
                    this.ReserveStatusField = value;
                    this.RaisePropertyChanged("ReserveStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvProgramBase", Namespace="http://schemas.datacontract.org/2004/07/iEPG.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewTvProgram.iEPGService.TvProgram))]
    public partial class TvProgramBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Attribute1Field;
        
        private string ComponentAudio1Field;
        
        private string ComponentVideo1Field;
        
        private string ContentTypeField;
        
        private string CopyControl1Field;
        
        private string DetailField;
        
        private System.DateTime EndDateTimeField;
        
        private string Genre1Field;
        
        private string Genre2Field;
        
        private System.Guid IdField;
        
        private string PerformerField;
        
        private string ProgramIdField;
        
        private string ProgramSubTitleField;
        
        private string ProgramTitleField;
        
        private System.DateTime StartDateTimeField;
        
        private string StationField;
        
        private string StationNameField;
        
        private string SubGenre1Field;
        
        private string SubGenre2Field;
        
        private byte[] TimestampField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attribute1 {
            get {
                return this.Attribute1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Attribute1Field, value) != true)) {
                    this.Attribute1Field = value;
                    this.RaisePropertyChanged("Attribute1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentAudio1 {
            get {
                return this.ComponentAudio1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentAudio1Field, value) != true)) {
                    this.ComponentAudio1Field = value;
                    this.RaisePropertyChanged("ComponentAudio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentVideo1 {
            get {
                return this.ComponentVideo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentVideo1Field, value) != true)) {
                    this.ComponentVideo1Field = value;
                    this.RaisePropertyChanged("ComponentVideo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyControl1 {
            get {
                return this.CopyControl1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CopyControl1Field, value) != true)) {
                    this.CopyControl1Field = value;
                    this.RaisePropertyChanged("CopyControl1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre1 {
            get {
                return this.Genre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Genre1Field, value) != true)) {
                    this.Genre1Field = value;
                    this.RaisePropertyChanged("Genre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre2 {
            get {
                return this.Genre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Genre2Field, value) != true)) {
                    this.Genre2Field = value;
                    this.RaisePropertyChanged("Genre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Performer {
            get {
                return this.PerformerField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformerField, value) != true)) {
                    this.PerformerField = value;
                    this.RaisePropertyChanged("Performer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramId {
            get {
                return this.ProgramIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramIdField, value) != true)) {
                    this.ProgramIdField = value;
                    this.RaisePropertyChanged("ProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramSubTitle {
            get {
                return this.ProgramSubTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramSubTitleField, value) != true)) {
                    this.ProgramSubTitleField = value;
                    this.RaisePropertyChanged("ProgramSubTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramTitle {
            get {
                return this.ProgramTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramTitleField, value) != true)) {
                    this.ProgramTitleField = value;
                    this.RaisePropertyChanged("ProgramTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationName {
            get {
                return this.StationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StationNameField, value) != true)) {
                    this.StationNameField = value;
                    this.RaisePropertyChanged("StationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubGenre1 {
            get {
                return this.SubGenre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubGenre1Field, value) != true)) {
                    this.SubGenre1Field = value;
                    this.RaisePropertyChanged("SubGenre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubGenre2 {
            get {
                return this.SubGenre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubGenre2Field, value) != true)) {
                    this.SubGenre2Field = value;
                    this.RaisePropertyChanged("SubGenre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="iEPGService.IiEPGService")]
    public interface IiEPGService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IiEPGService/GetTvPrograms", ReplyAction="http://tempuri.org/IiEPGService/GetTvProgramsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ViewTvProgram.iEPGService.TvProgram>> GetTvProgramsAsync(int days, int hours);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IiEPGServiceChannel : ViewTvProgram.iEPGService.IiEPGService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IiEPGServiceClient : System.ServiceModel.ClientBase<ViewTvProgram.iEPGService.IiEPGService>, ViewTvProgram.iEPGService.IiEPGService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IiEPGServiceClient() : 
                base(IiEPGServiceClient.GetDefaultBinding(), IiEPGServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IiEPGService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IiEPGServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IiEPGServiceClient.GetBindingForEndpoint(endpointConfiguration), IiEPGServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IiEPGServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IiEPGServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IiEPGServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IiEPGServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IiEPGServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ViewTvProgram.iEPGService.TvProgram>> GetTvProgramsAsync(int days, int hours) {
            return base.Channel.GetTvProgramsAsync(days, hours);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IiEPGService)) {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IiEPGService)) {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8082/iEPGService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return IiEPGServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IiEPGService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return IiEPGServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IiEPGService);
        }
        
        public enum EndpointConfiguration {
            
            NetTcpBinding_IiEPGService,
        }
    }
}
